export const cities = [
  'Delhi',
  'Mumbai',
  'Kolkata',
  'Bengaluru',
  'Chennai',
  'Hyderabad',
  'Ahmedabad',
  'Pune',
  'Jaipur',
];

export const categories = [
  '3D Printer',
  'Laser Cutting',
  'Vinyl Cutter',
  'CNC Router',
  'Laser Engraver',
  'Wood CNC',
  '3D Scanner',
  'Lathe Machine',
  'PCB Machine',
  'Soldering Station',
  '3D Printer',
  'Laser Cutting',
  'Vinyl Cutter',
  'CNC Router',
  'Laser Engraver',
  'Wood CNC',
  '3D Scanner',
  'Lathe Machine',
  'PCB Machine',
  'Soldering Station',
];